import Head from "next/head";
import Image from "next/image";
import SignInComponent from "@/components/home/SignUpComponent";

export default function SignUp() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-[100vw] h-[100vh] flex-type2">
                <div className="w-2/5 relative h-[100vh]  ">
                    <Image src="/homePic.png" layout="fill" alt="homepic" objectFit="cover" />
                </div>
                <SignInComponent />
            </div>
        </>
    );
}
